//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.10.13 at 11:07:44 PM CEST
//

package com.prodato.norma.demo.tomcat.utils;

import jakarta.xml.bind.annotation.XmlRegistry;


@XmlRegistry
public class MenuObjectFactory {

    public MenuObjectFactory() {
    }

    public Menu createMenu() {
        return new Menu();
    }

    public Menu.Menuitem createMenuMenuitem() {
        return new Menu.Menuitem();
    }

}
