//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.10.13 at 11:07:44 PM CEST
//

package com.prodato.norma.demo.tomcat.utils;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "title",
        "description",
        "menuitem"
})
@XmlRootElement(name = "menu", namespace = "http://www.example.org/NewXMLSchema")
public class Menu {

    @XmlElement(namespace = "http://www.example.org/NewXMLSchema", required = true)
    protected String title;
    @XmlElement(namespace = "http://www.example.org/NewXMLSchema")
    protected String description;
    @XmlElement(namespace = "http://www.example.org/NewXMLSchema", required = true)
    protected List<Menu.Menuitem> menuitem;

    public String getTitle() {
        return title;
    }

    public void setTitle(final String value) {
        title = value;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(final String value) {
        description = value;
    }

    public List<Menu.Menuitem> getMenuitem() {
        if (menuitem == null) {
            menuitem = new ArrayList<>();
        }
        return menuitem;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class Menuitem {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "url", required = true)
        protected String url;

        public String getValue() {
            return value;
        }

        public void setValue(final String value) {
            this.value = value;
        }

        public String getUrl() {
            return url;
        }

        public void setUrl(final String value) {
            url = value;
        }

    }

}
